"""initial

Revision ID: 9648e64ce3a2
Revises: 
Create Date: 2026-04-26 12:02:52.203539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9648e64ce3a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('autor', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('editora', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livro_ano'), 'livro', ['ano'], unique=False)
    op.create_index(op.f('ix_livro_autor'), 'livro', ['autor'], unique=False)
    op.create_index(op.f('ix_livro_editora'), 'livro', ['editora'], unique=False)
    op.create_index(op.f('ix_livro_titulo'), 'livro', ['titulo'], unique=False)
    op.create_index(op.f('ix_livro_uuid'), 'livro', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###