"""add user_id to livro

Revision ID: b8bddc539a4c
Revises: 70dcc93f5d50
Create Date: 2026-04-26 13:46:53.573608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bddc539a4c'
down_revision: Union[str, Sequence[str], None] = '70dcc93f5d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livro', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_livro_user_id'), 'livro', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livro_user_id'), table_name='livro')
    op.drop_column('livro', 'user_id')
    # ### end Alembic commands ###
